language: python
sudo: false

matrix:
  include:
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: pypy3
    - dist: xenial
      python: 3.7

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - pip install --upgrade setuptools
  - pip install -e .[test,xcb]

script:
  - python setup.py test
