language: python
sudo: false

matrix:
  include:
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: pypy3
    - dist: xenial
      python: 3.7

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

install:
  - pip install --upgrade setuptools
  - pip install -e .[test,xcb]

script:
  - python setup.py test
