language: python
sudo: false

matrix:
  include:
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: pypy3
    - dist: xenial
      python: 3.7

services:
  - xvfb

install:
  - pip install --upgrade setuptools
  - pip install -e .[test,xcb]

script:
  - python setup.py test
